version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-browsers

    working_directory: ~/circleci-python-automation

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest ui_tests --ignore=ui_tests/test_prepare_data.py -n 4 --dist=loadfile --reruns 2 -v --alluredir=test_results/allure
          when: always

      - run:
          name: clean test data
          command: |
            . venv/bin/activate
            python -m pytest -m clean
          when: always

      - store_artifacts:
          path: test-results
          destination: test-results
